cursoDjango/cursoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votacao/',include('votacao.urls'))
]

cursoDjango/votacao/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:pergunta_id>',views.votacao,name='votacao'),
    path('<int:pergunta_id>/votar',views.resultado, name='votar'),
    path('<int:pergunta_id>/resultado',views.resultado, name='resultado')

]

cursoDjango/votacao/models.py
from django.db import models

# Create your models here.
class pergunta(models.Model):
    texto = models.CharField(max_length=200)

    def __str__(self):
        return self.texto
    
class alternativa(models.Model):
    idPergunta = models.ForeignKey(pergunta,on_delete=models.CASCADE)
    texto = models.CharField(max_length=70)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.texto

cursoDjango/votacao/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from . import models
# Create your views here.

def index(request):
    perguntas = models.pergunta.objects.all()
    pacote = { 'perguntas' : perguntas}
    return render(request,'index.html',pacote)

def votacao(request,pergunta_id):
    pergunta = get_object_or_404(models.pergunta,pk=pergunta_id)    
    pacote = { 'pergunta' : pergunta }
    return render(request,'votacao.html', pacote)

def resultado(request,pergunta_id):
    return HttpResponse("Oi, eu sou o resultado")

cursoDjango/votacao/templates/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votação django</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

cursoDjango/votacao/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
<body>
    <ul class="list-group">
        {% for p in perguntas %}
        <li class="list-group-item">
            <a href="{% url "votacao" p.id %}"> {{p.texto}} </a>
        </li>
        {% endfor %}
    </ul>    
</body>
</html>

cursoDjango/votacao/templates/votacao.html
<!DOCTYPE html>
<html lang="PT-BR">
{% include "head.html" %}
<body>
    <a href="{% url 'index' %}"> voltar </a>
    <h1>{{pergunta.texto}}</h1>
    <form action="{% url 'votar' pergunta.id %}" method="post">
        {% csrf_token %}
        {% for alternativa in pergunta.alternativa_set.all %}
        <input type="radio" name="alternativa" id="{{alternativa.id}}" value="{{alternativa.id}}">
        <label for="alternativa">{{alternativa.texto}}</label> <br>
        {% endfor %}
        <button type="submit">Enviar voto</button>
    </form>

</body>
</html>